export default [
  {
    id: "1",
    title: "PlayStation 4 Slim 1TB Console - Jet Black",
    company: "Sony",
    priceWas: 1399.0,
    priceNow: 989.0,
    image: "/images/ps4.jpg",
  },
  {
    id: "2",
    title: "Ideapad Laptop With 11.6-Inch",
    company: "Lenovo",
    priceWas: 1099.0,
    priceNow: 999.0,
    image: "/images/laptop.jpg",
  },
  {
    id: "3",
    title: "55-Inch Frameless 4K UHD Smart LED TV (2020)",
    company: "Sony",
    priceWas: 1999.0,
    priceNow: 1328.95,
    image: "/images/tv.jpg",
  },
  {
    id: "4",
    title:
      "iPhone 11 Black 128GB 4G LTE (2020 - Slim Packing) - International Specs",
    company: "Apple",
    priceWas: 0,
    priceNow: 2699.0,
    image: "/images/iphone.jpg",
  },
  {
    id: "5",
    title: "Chromebook Laptop With 14-Inch Display",
    company: "Acer",
    priceWas: 1379.0,
    priceNow: 1175.0,
    image: "/images/chromebook.jpg",
  },
  {
    id: "6",
    title: "Switch Console (Extended Battery) - Neon",
    company: "Nintendo",
    priceWas: 1799.0,
    priceNow: 1177.8,
    image: "/images/nintendo.jpg",
  },
  {
    id: "7",
    title: "Galaxy A10s Dual SIM Red 32GB 2GB RAM 4G LTE - UAE Version",
    company: "Samsung",
    priceWas: 0,
    priceNow: 411.35,
    image: "/images/samsung.jpg",
  },
  {
    id: "8",
    title: "T120TWS True Wireless In-Ear Headphone Black",
    company: "JBL",
    priceWas: 299.0,
    priceNow: 158.8,
    image: "/images/jbl.jpg",
  },
];
